# Generated by Django 3.1.7 on 2021-03-31 08:49

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_wine_thumbnail'),
    ]

    operations = [
        TrigramExtension(),
        BtreeGinExtension(),
    ]
