# Generated by Django 3.1.7 on 2021-03-31 14:21

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210331_1011'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wine',
            name='catalog_wine_variety_gin_idx',
        ),
        migrations.RemoveIndex(
            model_name='wine',
            name='catalog_wine_winery_gin_idx',
        ),
        migrations.RemoveIndex(
            model_name='wine',
            name='catalog_wine_desc_gin_idx',
        ),
        migrations.AddField(
            model_name='wine',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='wine',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_vector_index'),
        ),
    ]
